pipeline{
    agent any

    environment {
        image_name = "jai129/${JOB_NAME}:${BUILD_NUMBER}"
    }

    stages{

        stage("Checkout SCM"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'python-jenkins-argocd-k8s']], userRemoteConfigs: [[credentialsId: 'jai', url: 'https://github.com/JaiLakshmanKumar/Jenkins-Projects.git']])            
            }
        }
        
        stage("Building docker image"){
            steps{
                sh '''
                echo 'Build Docker Image'
                ls -ltr 
                cd ./python-jenkins-argocd-k8s && docker buildx build -t $image_name .
                '''
            }
        }

        stage("Pushing the artifact"){
            steps{

                withCredentials([usernamePassword(
                    credentialsId: 'Docker-Credentials',
                    passwordVariable: 'DOCKER_PASS',
                    usernameVariable: 'DOCKER_USER'
                )]) {
                    sh '''
                    echo 'Logging in to docker hub'
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    echo 'Push to registry'
                    docker push $image_name
                    '''
                }
                
            }
        }

        stage("Checkout K8 manifest"){
            step{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'jai', url: 'https://github.com/JaiLakshmanKumar/jenkins-projects-cicd-manifest-repo.git']])
            }
        }

        stage("updating deployment file"){
            step{
                sh '''
                cat deployment.yaml
                sed -i '' "s|image:.*|image: $image_name|g" deployment.yaml 
                cat deployment.yaml
                git add deployment.yaml
                git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                git remote -v
                git push https://github.com/JaiLakshmanKumar/jenkins-projects-cicd-manifest-repo.git HEAD:main
                '''
            }
        }

    }
}