FROM eclipse-temurin:17-jre-alpine

# 2. Set the working directory inside the container
WORKDIR /app

# 3. Copy the JAR from your 'target' folder into the container
COPY target/*.jar app.jar

# 4. Tell Docker how to start the app
ENTRYPOINT ["java", "-jar", "app.jar"]