pipeline {
  agent {
    docker { 
      image 'jai129/jai-java-maven-docker-cli-agent:v2' 
      args '-v /var/run/docker.sock:/var/run/docker.sock'
    }
  }
  environment {
        // This tells Maven: "Your home is here, in the workspace I own"
        HOME = "${env.WORKSPACE}"
    }
  stages {
    stage('Build jar file') {
      
      steps {
        // Use 'mvn', not 'maven'
        echo "Building the application..."
        sh 'ls -ltr'
        sh 'chmod +x ./my-first-pipeline/mvnw '
        sh 'cd my-first-pipeline && ./mvnw clean package' 
      }
    }
    stage('Build Docker Image'){
      steps{
        echo "Building docker image"
        sh 'docker --version'
        sh 'docker buildx build -t simple-java-app ./my-first-pipeline'
      }
    }
    stage('Run docker file'){
      environment {
        // This tells Maven: "Your home is here, in the workspace I own"
        HOME = "${env.WORKSPACE}"
    }
      steps{
        echo "Running docker image"
        sh 'docker run -p 5432:5432 --name my-app simple-java-app'
        sh "curl 'http://localhost:5432'" 
      }
    } 
  }
  post{
    always{
      sh 'docker rm -f my-app || true'
    }
  }
  
}