pipeline {
  agent {
    docker { 
      image 'abhishekf5/maven-abhishek-docker-agent:v1' }
  }
  stages {
    stage('Test') {
      steps {
        // Use 'mvn', not 'maven'
        sh 'mvn --version'
      }
    }
  }
}